### ISSUE TITLE
Function to fold / map / traverse split keys

### ISSUE THREAD

**Issue by adamflott** [glguy/tries#3]
[ Feel free to close if this breaks the spirit of generic-trie ]

I'd like functions to walk the split keys and potential value (as opposed to foldWithkey which operates on the full key). My goal is to leverage the Data.GenericTrie work to convert the in memory trie into a suitable JSON representation for my data type.

**Comment by glguy** [comment]
Do you have an example input and output you had in mind for how this would look?

**Comment by adamflott** [comment]
Given "/a/b/c" -> [1,2] , "/a/b/d" -> [3, 4] as keys, values, I'd like to have a function that would give

1. "a"
2. "b"
3. "c", [1,2]
4. "d", [3,4]

Ultimately I'm after making the ToJSON instances easy to write.

**Comment by glguy** [comment]
This type isn't really going to be able to support this operation

**Comment by adamflott** [comment]
Bummer.
